services:
  customer-postgres:
    container_name: customer-postgres
    restart: always
    image: postgres

    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "customer"
      POSTGRES_DB: "customer"
      POSTGRES_PASSWORD: "SuperPassword@2"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - customer-postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker